---
docker_dependencies:
  - acl
  - python3-pip
  - python3-docker
  - python3-requests
  - python3-urllib3
  - python3-virtualenv
  - python3-venv
  - net-tools
  - iproute2
  - gpg

docker_packages:
  - containerd.io
  - docker-ce
  - docker-buildx-plugin
  - docker-ce-cli
  - docker-ce-rootless-extras
  - docker-compose-plugin
  - docker-scan-plugin

## choose centos docker repo channel enable status
docker_repo:
  channel:
    stable_enabled: true
    test_enabled: false
    nightly_enabled: false
  gpg_url: https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg  # https://repo.yourdomain.ir/repository/debian-docker/gpg   # 
  repo_url: https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower  }}     # https://repo.yourdomain.ir/repository/debian-docker/    
      #for debian  https://download.docker.com/linux/debian/gpg #for ubuntu https://download.docker.com/linux/ubuntu/gpg
      #for debian https://download.docker.com/linux/debian      #for ubuntu https://download.docker.com/linux/ubuntu

docker_config:
  proxy:
    enable: false
    http_url: "http://127.0.0.1:8123"
    https_url: "http://127.0.0.1:8123"
    no_proxy_url: "hub.yourdomain.ir,127.0.0.0/8"
  logging:
    enable: true
    labels: "{{ inventory_hostname }}"
    max_file: 5
    max_size: 100M
  mirror_registry:
    enable: false
    urls: "https://hub.yourdomain.ir"
  insecure_registry:
    enable: false
    urls: "https://test.yourdomain.ir"
  live_restore:
    enable: true
  experimental:
    enable: true
