all:
  vars:
    ansible_user: root
    ansible_port: 22
    ansible_python_interpreter: /usr/bin/python3
  children:
    tools_servers:
      hosts:
        hysteria_proxy:
          ansible_host: 91.98.20.28
        
