# main domain address
main_domain: yourdomain

# main project directory
project_dir: /opt/services


#hysteria image version
image_tag: v2.6.2
#Hysteria_configuratin file's parameters
proxy_domain: "cookie.{{ main_domain }}"
hysteria_port: 2211


#iptables
#Enable this parameter if you want to forward traffic from port 443 to the Hysteria service running on a different port
redirect_443_to_port: true