#SPDX-License-Identifier: MIT-0
---
# handlers file for docker
- name: restart docker
  service:
    name: docker
    state: restarted
    enabled: true
  when: ansible_facts['os_family'] == 'Debian' 


- name: restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
    enabled: true
  when: ansible_facts['os_family'] == 'Debian' 